CREATE TABLE [dbo].[Sandwiches]
(
	[Key] int NOT NULL,
    [Fillings] nvarchar(2000) NOT NULL, 
	[Condiments] nvarchar(2000) NOT NULL,
	[Cost] int NOT NULL,
	[MealPower1] nvarchar(2000) NOT NULL,
	[MealPower2] nvarchar(2000) NOT NULL,
	[MealPower3] nvarchar(2000) NOT NULL,
	[Taste] nvarchar(2000) NOT NULL,
	[Sweet] int NOT NULL,
	[Salty] int NOT NULL,
	[Sour] int NOT NULL,
	[Bitter] int NOT NULL,
	[Hot] int NOT NULL,
	[Egg] int NOT NULL,
	[Catching] int NOT NULL,
	[Exp] int NOT NULL,
	[Raid] int NOT NULL,
	[ItemDrop] int NOT NULL,
	[Humungo] int NOT NULL,
	[Teensy] int NOT NULL,
	[Encounter] int NOT NULL,
	[Title] int NOT NULL,
	[Sparkling] int NOT NULL,
	[Normal] int NOT NULL,
	[Fighting] int NOT NULL,
	[Flying] int NOT NULL,
	[Poison] int NOT NULL,
	[Ground] int NOT NULL,
	[Rock] int NOT NULL,
	[Bug] int NOT NULL,
	[Ghost] int NOT NULL,
	[Steel] int NOT NULL,
	[Fire] int NOT NULL,
	[Water] int NOT NULL,
	[Grass] int NOT NULL,
	[Electric] int NOT NULL,
	[Psychic] int NOT NULL,
	[Ice] int NOT NULL,
	[Dragon] int NOT NULL,
	[Dark] int NOT NULL,
	[Fairy] int NOT NULL,	
    CONSTRAINT [PK_Sandwiches] PRIMARY KEY ([Key])
)
